export const issues = [
  {
    id: "bogota",
    name: "Bogotá, D.C.",
    department: "Distrito Capital",
    description: "La Atenas suramericana",
    architecture: ["Neoclásico", "Republicano", "Moderno"],
    population: 7878783,
    bgColor: "#d83625",
    poster: "assets/images/Bogota.avif",
    coordinates: { lat: 4.711, lng: -74.0721 },
  },
  {
    id: "medellin",
    name: "Medellín",
    department: "Antioquia",
    description: "La Ciudad de la Eterna Primavera",
    architecture: ["Contemporáneo", "Urbano", "Innovador"],
    population: 2549537,
    bgColor: "#ff7f0e",
    poster: "assets/images/Medellin.avif",
    coordinates: { lat: 6.2442, lng: -75.5812 },
  },
  {
    id: "cali",
    name: "Cali",
    department: "Valle del Cauca",
    description: "La Sucursal del Cielo",
    architecture: ["Colonial", "Moderno", "Tropical"],
    population: 2227642,
    bgColor: "#0e4972",
    poster: "assets/images/Cali.avif",
    coordinates: { lat: 3.4516, lng: -76.532 },
  },
  {
    id: "barranquilla",
    name: "Barranquilla",
    department: "Atlántico",
    description: "La Puerta de Oro de Colombia",
    architecture: ["Republicano", "Art Decó", "Moderno"],
    population: 1286364,
    bgColor: "#481251",
    poster: "assets/images/Barranquilla.avif",
    coordinates: { lat: 10.9685, lng: -74.7813 },
  },
  {
    id: "cartagena",
    name: "Cartagena de Indias",
    department: "Bolívar",
    description: "La Heroica",
    architecture: ["Colonial", "Republicano", "Moderno"],
    population: 1028736,
    bgColor: "#eb6150",
    poster: "assets/images/Cartagena.avif",
    coordinates: { lat: 10.391, lng: -75.4794 },
  },
  {
    id: "cucuta",
    name: "Cúcuta",
    department: "Norte de Santander",
    description: "La Puerta de Colombia",
    architecture: ["Colonial", "Moderno"],
    population: 755098,
    bgColor: "#bcbd22",
    poster: "assets/images/Cucuta.avif",
    coordinates: { lat: 7.8891, lng: -72.496 },
  },
  {
    id: "bucaramanga",
    name: "Bucaramanga",
    department: "Santander",
    description: "La Ciudad de los Parques",
    architecture: ["Republicano", "Moderno", "Contemporáneo"],
    population: 632929,
    bgColor: "#0f824c",
    poster: "assets/images/Bucaramanga.avif",
    coordinates: { lat: 7.1193, lng: -73.1227 },
  },
];
